### ISSUE TITLE
Data License

### ISSUE THREAD

**Issue by missinglink** [google/libaddressinput#155]
Hi,

How is the `AddressValidationMetadata` data licensed?

I see that the software is licensed as `Apache License 2.0` and the metadata is referred to as 'publicly available' and 'open source', what exactly is the license for that data?

I would like to know if I can include the data in my application and if so, what the requirements are for attribution and sharealike?

- https://github.com/googlei18n/libaddressinput/wiki/AddressValidationMetadata
- https://chromium-i18n.appspot.com/ssl-address

**Comment by rsolomakhin** [comment]
@lararennie, @roubert: It's public domain, right?

**Comment by roubert** [comment]
Sorry, but I don't really know anything about this data.

**Comment by missinglink** [comment]
thanks for the reply, if the data is public domain or CC0, would it be possible to add a license file to the `appspot` site?

that way if I copied the files, I could include a copy of the license file which would also ensure that the contributors are properly credited for their work.

**Comment by rsolomakhin** [comment]
@madmath: Do you think that's possible?

**Comment by bojanz** [comment]
I was told on the mailing list when I was starting https://github.com/commerceguys/addressing that the dataset was public domain. Hence me scrapping it and committing it to an MIT library.

**Comment by ahukkanen** [comment]
Could someone who has the contact information of any of the current project owners get this cleared out? I have no idea who is the current owner and don't know who to contact frankly.

It would be really helpful to have the data licensing information publicly listed on the wiki page, so there would not be any confusions. Now the only source of information is a private mailing list (which I cannot read for instance) and there is no definitive answer to this.

**Comment by lararennie** [comment]
Anyone can join the mailing list: it's only locked down so it doesn't get spam...

**Comment by ahukkanen** [comment]
Ah, thanks @lararennie! Got some permission errors from the links so I didn't know where to join. I googled the group and got to the front page where I could join.

**Comment by HAAKS** [comment]
@ahukkanen I cant join the group, it just shows that it doesn't exist. Would you mind adding me or who to contact to be added?

**Comment by sockix** [comment]
Thank you for asking. 

The GitHub project and the appspot service have been updated.

In case you missed it though, it's basically:

Source code licensed under the Apache 2.0. Data licensed under the CC-BY 4.0
