### ISSUE TITLE
Indonesian provinces not required

### ISSUE THREAD

**Issue by mimckenna** [google/libaddressinput#164]
It appears that "Province" in Indonesia is either not required, or not used at all.

- Google address data reference: https://chromium-i18n.appspot.com/ssl-address/data/ID
- Also refer to issue #60 

Wikipedia says [province is optional in Indonesia](https://en.wikipedia.org/wiki/Address_(geography)#Indonesia).

[UPU for Indonesia](http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/idnEn.pdf) says Province is "\[n]ot used in address".
![image](https://user-images.githubusercontent.com/11297262/41259036-fce767a8-6d86-11e8-9e2c-6c0515314c6d.png)

And according to [PitneyBowes](http://support.pb.com/help/spectrum/9.0/pdf/en/Spectrum_9.0_Geocoding_IDN.pdf) Indonesian geocoding software specs (page 13), "State/Province ... is not used for this country."

Graham Rhind's [Global Sourcebook for International Data Management](https://www.grcdi.nl/gsb/indonesia.html#HEF805F62949F18E77450FF5F7F2B06C3B319F50B044A2AA2AIndonesiaA20A2DA20A5BA5BAdministrativeA20districtsA5DA5DA2AA2A00100401001301601901C02D03903C03F042) states that in Indonesia, "Administrative districts ... provinces ... are not used in addresses."

When searching trough ALL the example addresses submitted by the Indonesian Postal Authority to UPU, not one of them includes a province.
Indonesia S42 Standardized Address Format Description as submitted to UPU: [idn.pdf](https://github.com/googlei18n/libaddressinput/files/2091864/idn.pdf). Note "Region" (or Province) is missing in the list of S42 elements used.

But, the Google libaddressinput metadata shows not only is province included, but it's required:
```
{
    ...
    "zip": "\\d{5}",
    "require": "AS",
    "name": "INDONESIA",
    "lang": "id",
    "fmt": "%N%n%O%n%A%n%C%n%S %Z",
    ...
}
```

perhaps the metadata should be changed to the following?

```
{
    ...
    "zip": "\\d{5}",
    "require": "A",
    "name": "INDONESIA",
    "lang": "id",
    "fmt": "%N%n%O%n%A%n%C %Z",
    ...
}
```

Cheers,

Mike McKenna

**Comment by sockix** [comment]
Hi. My understanding is that the province is written if the person searching or writing the address is in another province. Since the metadata (and widget) isn't aware of this context, we always include it (as required).  

In addition, since we have the defined listed of provinces, having the field required should hopefully be problematic,
