### ISSUE TITLE
Requests for Jamaica (JM) is returning a 404

### ISSUE THREAD

**Issue by JayTurn** [google/libaddressinput#180]
It appears as though Jamaica is returning a 404 error when being requested via the following uri:

https://www.gstatic.com/chrome/autofill/libaddressinput/chromium-i18n/ssl-address/data/JM

I'm not entirely sure why as the country code still exists in the official chromium address data:

https://chromium-i18n.appspot.com/ssl-address/data

**Comment by madmath** [comment]
The second URL is the canonical source. Append /JM for example. gstatic gets redirected to as an optimization, for some keys.

**Comment by JayTurn** [comment]
Ah that makes sense, thanks @madmath.
