### ISSUE TITLE
Update country code for Cork, Ireland

### ISSUE THREAD

**Issue by Flexo013** [google/libaddressinput#187]
According to <https://www.gstatic.com/chrome/autofill/libaddressinput/chromium-i18n/ssl-address/data/IE> the ISO 3166-2 county code for Cork, Ireland is `IE-C`. (4th sub_key and 4th sub_isoid)

As of 2011-12-13 this has been updated to `IE-CO` in order to prevent confusion with the province Connaught, which has the code `IE-C`. For more info see <https://en.wikipedia.org/wiki/ISO_3166-2:IE> and <https://www.iso.org/files/live/sites/isoorg/files/archive/pdf/en/iso_3166-2_newsletter_ii-3_2011-12-13.pdf> (page 39)

**Comment by sockix** [comment]
fixed
