### ISSUE TITLE
sub_zips Issue with South Korea

### ISSUE THREAD

**Issue by fragglebob** [google/libaddressinput#192]
Daegu's regex at country level address data, does not match Dalseong-gun correctly, unlike the regexs available at admin level.

Daegu (대구광역시) - 4[12]\d{2} - https://www.gstatic.com/chrome/autofill/libaddressinput/chromium-i18n/ssl-address/data/KR
Dalseong-gun (달성군) - 4(?:29|30) - https://chromium-i18n.appspot.com/ssl-address/data/KR/%EB%8C%80%EA%B5%AC%EA%B4%91%EC%97%AD%EC%8B%9C

**Comment by rsolomakhin** [comment]
Thank you for the bug report. We are triaging this issue.

**Comment by sockix** [comment]
Thx. Fixed.
