### ISSUE TITLE
County is missing from UK

### ISSUE THREAD

**Issue by Dreamsorcerer** [google/libaddressinput#193]
Downstream bug reports:
https://bugzilla.mozilla.org/show_bug.cgi?id=1624741
https://bugs.chromium.org/p/chromium/issues/detail?id=1064656

It seems the county field does not exist when the country is set to the UK. This is a common field on most address forms during checkout.

This should be able to use the region/state field used for other countries, just with the display name changed to County.

**Comment by sockix** [comment]
Thanks for the feedback. 

I looked into this a bit, and according to the Royal Mail the county name is not necessary. 

See: https://personal.help.royalmail.com/app/answers/detail/a_id/81/~/how-to-address-your-mail-%28clear-addressing%29

Cheers!

**Comment by Dreamsorcerer** [comment]
But, why ignore it, when it is on every checkout form? You are just making the user type it in manually everytime.

For example, go to the checkout at boots.com (a UK company), and enter the postcode "BN1 9HT", and you'll see that there is a county field that is prefilled. Almost every checkout form has this field, and it is frequently written on letters and parcels.

I've successfully had forms fill correctly, by not setting the country to UK, and just entering it in the region field. It already works correctly, you only need to copy the region field to UK (and change the display name).

**Comment by Dreamsorcerer** [comment]
I've had 2 different websites today fail to autocomplete correctly because the county field was required.

Just because it's not strictly needed doesn't mean there should be no effort to fill it in when requested, this is just a poor user experience.
