### ISSUE TITLE
Ireland postcode should be on its own line

### ISSUE THREAD

**Issue by anssih** [google/libaddressinput#202]
Currently in the formatted output the Irish country and postcode (eircode) are on the same line, separated by space:

Co. Cork A12 B3CD

However, according to various official sources (https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/irlEn.pdf, https://www.eircode.ie/faqs section "Where should I write the Eircode on a letter?") and unofficial sources (e.g. https://www.quora.com/What-is-the-mailing-address-format-for-Ireland), it should go after the county on a separate line:

Co. Cork
A12 B3CD

This is similar how it works in e.g. UK.

I.e. the format code should be changed as follows:

"%N%n%O%n%A%n%D%n%C%n%S %Z" => "%N%n%O%n%A%n%D%n%C%n%S%n%Z"

**Comment by sockix** [comment]
Thanks for the feedback. 

This has been updated.
