### ISSUE TITLE
Ireland requires addressline1, locality, subdivision

### ISSUE THREAD

**Issue by damienmckenna** [google/libaddressinput#235]
Addresses in Ireland require an addressLine1, locality and subdivision, the system does not indicate this.

**Comment by damienmckenna** [comment]
I believe the appropriate change would be to add this to the IE file:

    "require":"1CS"

**Comment by bojanz** [comment]
https://github.com/commerceguys/addressing/issues/189#issuecomment-1441932529

**Comment by damienmckenna** [comment]
I forgot there's a minor complication that negates this:

* In cities they can just specify the city name and not need to include the county name, e.g. the University of Limerick's address is: "University of Limerick, Castletroy, Limerick", and not "University of Limerick, Castletroy, County Limerick".

Never mind 🤦
