### ISSUE TITLE
Dealing with countries that use only one address line

### ISSUE THREAD

**Issue by bojanz** [google/libaddressinput#61]
I've received reports from users in several countries\* that the second address line is not used in their countries.  And indeed, going to the sites of the AU & NZ post offices, only one line is rendered.

Was there ever a plan to split the %A token in the dataset into multiple tokens (one per address line)? I'm not sure how feasible such a thing would be (from a data gathering perspective, especially), but it's worth a discussion.
- Australia, Estonia, Latvia, Lithuania, New Zealand, Russia, Finland

**Comment by sockix** [comment]
There are no plans to break the %A token up.

AFAIK, there was a point in time when we use to show line 1 and line 2 as separate tokens, but have since gone away from that... so I highly doubt we'll break them up again.
